name: Flutter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  check_commit_msg:
    outputs:
      commit_message: ${{ steps.get_message.outputs.message }}
    name: Check if the workflow has been disabled.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get commit message
        id: get_message
        run: |
          echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.after }} | tr '\n' ' ')"
          echo "message=\"$(git log --format=%B -n 1 ${{ github.event.after }} | tr '\n' ' ')\"" >> $GITHUB_ENV
  build_apk:
    needs: check_commit_msg
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
      # Please seehttps://imuer8.blogspot.com/2024/01/sail-vpn.html
        java-version: ${{vars.SAIL_JAVA_VISION}}
    - uses: subosito/flutter-action@v2
      with:
      # Please see https://imuer8.blogspot.com/2024/01/sail-vpn.html
        flutter-version: ${{vars.SAIL_FLUTTER_VERSION}}
    - run: dart --version
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk
    - name: Rename APK
      run: |
        cd build/app/outputs/flutter-apk
        mv app-release.apk marsix.apk
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sail.${{ github.sha }}.android
        path: build/app/outputs/flutter-apk/marsix.apk
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v1.0.0
        release_name: Release v1.0.0

  build_ios:
    needs: check_commit_msg
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{vars.SAIL_JAVA_VISION}}
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{vars.SAIL_FLUTTER_VERSION}}
    - run: dart --version
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sail.${{ github.sha }}.ios
        path: build/ios/iphoneos/Runner.app
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/ios/iphoneos/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v1.0.0
        release_name: Release v1.0.0
